### ISSUE TITLE
Create functionality  of RegisterFlightScreen 

### ISSUE THREAD

**Issue by CalixtoSD117** [BrightCoders-Institute/s4a1-reservaci-n-de-vuelos-s4a1-reservacion-de-vuelos-team-3#16]
# REQUIREMENTS / DESCRIPTION

In this part need implement the code for keep the data in the different screens of register and send the data at Firebase.

## Tasks

- [ ] send the data at Firebase 
- [ ] Keep the data in the screens
- [ ] correctly save data
